// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ClearScanHistory() {
  return window['go']['main']['App']['ClearScanHistory']();
}

export function DeleteScanHistoryRecord(arg1) {
  return window['go']['main']['App']['DeleteScanHistoryRecord'](arg1);
}

export function DetectTools() {
  return window['go']['main']['App']['DetectTools']();
}

export function ExportScanHistoryRecord(arg1, arg2) {
  return window['go']['main']['App']['ExportScanHistoryRecord'](arg1, arg2);
}

export function LoadNmapHelp() {
  return window['go']['main']['App']['LoadNmapHelp']();
}

export function OpenNmapDownloads() {
  return window['go']['main']['App']['OpenNmapDownloads']();
}

export function OpenNmapNSEDocs() {
  return window['go']['main']['App']['OpenNmapNSEDocs']();
}

export function OpenNmapReferenceGuide() {
  return window['go']['main']['App']['OpenNmapReferenceGuide']();
}

export function PreviewScan(arg1) {
  return window['go']['main']['App']['PreviewScan'](arg1);
}

export function ScanHistory() {
  return window['go']['main']['App']['ScanHistory']();
}

export function ScanProfiles() {
  return window['go']['main']['App']['ScanProfiles']();
}

export function ScanReport(arg1) {
  return window['go']['main']['App']['ScanReport'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}
