// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform} from '../models';
import {exporter} from '../models';
import {scanner} from '../models';
import {store} from '../models';
import {version} from '../models';

export function AppVersion():Promise<version.Info>;

export function CancelScan():Promise<boolean>;

export function ChooseNmapPath():Promise<string>;

export function ClearScanHistory():Promise<void>;

export function DeleteScanHistoryRecord(arg1:string):Promise<void>;

export function DetectTools():Promise<Array<platform.ToolDetection>>;

export function DetectNmapPath(arg1:string):Promise<platform.ToolDetection>;

export function ExportScanHistoryRecord(arg1:string,arg2:exporter.Format):Promise<string>;

export function LoadNmapHelp():Promise<platform.ToolHelp>;

export function OpenNmapDownloads():Promise<void>;

export function OpenNmapNSEDocs():Promise<void>;

export function OpenNmapReferenceGuide():Promise<void>;

export function PreviewScan(arg1:scanner.ScanRequest):Promise<scanner.CommandPreview>;

export function ScanHistory():Promise<Array<store.ScanRecord>>;

export function ScanProfiles():Promise<Array<scanner.Profile>>;

export function ScanReport(arg1:string):Promise<string>;

export function StartScan(arg1:scanner.ScanRequest):Promise<scanner.ScanStarted>;
